sudo: false
language: ruby
rvm:
  - 2.1.5
  - 2.2.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
addons:
  postgresql: "9.3"
bundler_args: "--jobs=3 --retry=3 --without development:production --deployment"
cache: bundler

before_install:
  - gem update bundler

before_script:
  - psql -c 'create database coursemology_test;' -U postgres
  - bundle exec rake db:setup

script:
  - bundle exec consistency_fail
  - bundle exec rake spec
